### ISSUE TITLE
Inaccurate link in Configuring S3 Storage Doc

### ISSUE THREAD

**Issue by xnastasia** [urbit/docs#1054]
[Configuring S3 Storage](https://urbit.org/using/os/s3/) instructs (in the **Add your credentials: Landscape** section) to navigate to `https://<your-ship-url>/~profile/settings` when the correct link would be `https://<planet-username-id-thingy>.tlon.network/~settings#s3`

**Comment by galenwp** [comment]
Good catch. 

We probably want to update to `https://<your-ship-url>/~settings#s3` since your ship could be hosted by someone other than `tlon.network`.
