### ISSUE TITLE
FAQ Page Needs to be Split Up and have a Link Index like a Wikipedia Page

### ISSUE THREAD

**Issue by tacryt-socryp** [urbit/docs#1065]
This page is one of the worst in the whole documentation (not the content, but it's massive and impossible to navigate)

**Comment by matildepark** [comment]
it does...on the left

**Comment by tacryt-socryp** [comment]
It does not on mobile. A lot of these pages need to be viewed on mobile and be optimized.

**Comment by matildepark** [comment]
There's a whole mobile navigation element we use on docs we could easily port to the page_indiced template. *shrug* In which case it's better filed as an urbit.org issue.

**Comment by tacryt-socryp** [comment]
Regardless, I don't think this should be one page. This seems better as a directory page in the same style as the top-level docs page

https://urbit.org/docs/

**Comment by tacryt-socryp** [comment]
resolved in gold
