### ISSUE TITLE
Source code listing for `+malt` seems to be erroneous

### ISSUE THREAD

**Issue by ynx0** [urbit/docs#1071]
Title. 

See https://github.com/urbit/docs/blob/3d60a5a2ffd6aea020219c50cfe9087c4dae4992/hoon/reference/stdlib/2l.md , which currently shows
```
:-  :~  navhome/'/docs/'
        sort/'14'
        title/'2k: Jar and Jug Logic'
    ==

;>
```

According to https://github.com/urbit/urbit/blob/42bde744d8f1dbfe8c6ec13b086687d6714748e3/pkg/arvo/sys/hoon.hoon#L1923-L1926 ,
it seems like it should be:
```hoon
++  malt
  |*  a=(list)
  (molt `(list [p=_-<.a q=_->.a])`a)
```

**Comment by drbeefsupreme** [comment]
Thanks!
