### ISSUE TITLE
Colhep as a tuple in Hoon Style guide has markdown typo

### ISSUE THREAD

**Issue by thelifeandtimes** [urbit/docs#1086]
In the final paragraph of this section: https://urbit.org/docs/hoon/reference/style/#fixed-sequences-and-backstep-indentation

the list of runes that are tuples includes `:-,` but it should be `:-`, with the comma outside the code element.

**Comment by drbeefsupreme** [comment]
Thanks! https://github.com/urbit/docs/commit/f99a557141495c001e5c5f67bc328989df4b1529
