### ISSUE TITLE
unable to install libsigsegv-devel on Amazon Linux

### ISSUE THREAD

**Issue by joemfb** [urbit/docs#112]
With regards to http://urbit.org/docs/using/install/,

I tried recently, and wasn't able to resolve the package, even with yum --enablerepo epel.

I was able to build urbit by manually installing libsigsegv from source -- I just thought the absence of the package should be noted here.

**Comment by galenwp** [comment]
Thanks for reporting this.  I feel like we should just provide a public AMI.  Thoughts?

**Comment by ohAitch** [comment]
A dockerfile would probably make more sense, if the network issues got
resolved

**Comment by galenwp** [comment]
Isn't it much, much simpler to just launch a specific AMI?

**Comment by cgyarvin** [comment]
Galen is right.

**Comment by galenwp** [comment]
I'm all for providing a dockerfile as well. And fixing the related networking issues.
