### ISSUE TITLE
docs html underline rendered too low in Firefox

### ISSUE THREAD

**Issue by heow** [urbit/docs#118]
<img width="1178" alt="screen1" src="https://cloud.githubusercontent.com/assets/137922/22441085/e68839c0-e703-11e6-82cc-26b5882f99e9.png">

**Comment by heow** [comment]
Looks like it's this CSS controlling it, in the codemirror-fonts-bootstrap-tree.css:7768

.sections h1:first-of-type {
    padding-bottom: 1rem;
}

Looks like a lib, poking around to see if it's easily overridden locally.

**Comment by galenwp** [comment]
Yep, that sounds right.  I think we're bundling our css — it's probably from https://github.com/urbit/tree/blob/master/css/_sections.scss

**Comment by galenwp** [comment]
I think this should be fixed.
