### ISSUE TITLE
Tiny lil' misspelling in 'Layout' doc page

### ISSUE THREAD

**Issue by edouerd** [urbit/docs#119]
https://github.com/urbit/docs/blame/master/docs/using/layout.md#L94

'Default web **requets**' => 'Default web **requests**'

That's all ✔️

**Comment by hoclun-rigsep** [comment]
Addressed in upcoming pr

**Comment by cgyarvin** [comment]
Thanks both!

**Comment by galenwp** [comment]
@hoclun-rigsep how's that PR coming?

**Comment by hoclun-rigsep** [comment]
It's coming but I'll be away and won't be able to submit until Saturday or perhaps Sunday.

**Comment by galenwp** [comment]
Totally fine! Just checking. Was in the docs today.
