### ISSUE TITLE
Copy fix: Community/Contact list item on front page

### ISSUE THREAD

**Issue by edouerd** [urbit/docs#146]
Here again with a tiny edit needed on http://urbit.org/docs/ —

<img width="393" alt="screen shot 2017-02-14 at 1 06 26 am" src="https://cloud.githubusercontent.com/assets/1195363/22917290/d519290c-f251-11e6-839e-0786c65735da.png">

In the second bullet, `discussion forumon` are running into one another.

That's it!

**Comment by xykj61** [comment]
Fixed this with a recent PR that should be merged into Master now. Just haven't pushed to our web ship, but we'll do that today. Thanks!

**Comment by urcades** [comment]
most excellent — good to know!
