### ISSUE TITLE
Latest release

### ISSUE THREAD

**Issue by Fang-** [urbit/docs#168]
The [installation instructions](https://github.com/urbit/docs/blob/master/docs/using/install.md) link to files with version numbers in their name. We could update these manually for every release, but either of the following solutions seem more robust to me.

* Link to `media.urbit.org/dist/xyz/latest.file` instead, and set up a small script to copy in the latest release from the [GitHub releases page](https://github.com/urbit/docs/blob/master/docs/using/install.md) whenever it gets added.
* Just plainly link to the GitHub releases page from the docs and/or refer to package managers. (I have heard rumors of `brew` containing a non-latest version of Urbit, we may want to automate releasing to package managers as well if at all possible.)

**Comment by xykj61** [comment]
This has effectively been solved by electing to have people build from source for now. We're also working on install and upgrade scripts for Vere that will automate pulling the latest urbit/urbit master code and making the new binary. WIP.

**Comment by ohAitch** [comment]
Oh, so we're no longer going to be uploading a `.deb`?
