### ISSUE TITLE
Glossary Organization

### ISSUE THREAD

**Issue by joshuareagan** [urbit/docs#202]
I'm going to start adding some definitions to the glossary---it's pretty short right now.  But the organization seems a bit haphazard.  In a way it seems like there are sections: a ship section, a Nock section, and a Hoon section---but these seem not to have much internal order.  I'm sure most people use something like ctrl+f to find what they want anyway, but it still seems like we should clean this thing up.

Alphabetical order seems like the natural choice.  Some things we can group together---it would be a shame to break up the Nock section, say---but otherwise alphabetical?  Thoughts?

**Comment by galenwp** [comment]
I think alphabetical order per-section makes sense.  It'd also be nice if each definition had an id so you could `#link` to it.

**Comment by joshuareagan** [comment]
Good idea.

**Comment by joemfb** [comment]
This time around, I am choosing to have no dog in this fight. Historical context is here: https://groups.google.com/forum/#!topic/urbit-dev/bjQ2B767yS8.

**Comment by joshuareagan** [comment]
The glossary is a reference document, not a tutorial, so I think alphabetizing it makes the most sense.  I'm not a hug fan of the sections, though I understand why others like them.  But for a glossary, the three main priorities should be (1) formal correctness, (2) completeness of coverage, and (3) it's easy to look up a term on the page.  Naturally most people will use ctrl+f anyway, but it's standard practice to alphabetize as well.

**Comment by xykj61** [comment]
Yeah, you're right. K, I'll merge your stuff. Thanks!
