### ISSUE TITLE
Friends of FizzBuzz exercise two is unfair :)

### ISSUE THREAD

**Issue by bvschwartz** [urbit/docs#22]
This is the one where you have to figure out how to pass two parameters to a gate. I believe the answer is just

```
|=  {start/atom end/atom}
```

(Maybe there is a better way?) However it is not clearly documented in the hoon docs as far as I can see. I suppose it can be figured out by implication. Perhaps the syntax section should talk about the syntax for creating some basic things like numbers, strings, cells/tuples, and whatever you call the {} construct. I don't think the {} syntax is ever discussed.

[edit: ignore this part about comments as it is already there] This should probably be a separate issue: but it would be really nice if there was a comment section at the bottom of each page for a lower friction way of providing comments.

**Comment by galenwp** [comment]
I see a comments box here: http://urbit.org/docs/hoon/exercises/fizzbuzz/, but do you mean on each documentation page?  (@philipcmonk is the person to answer the rest of your question)

**Comment by bvschwartz** [comment]
Doh! Never mind that part about a comment. I somehow missed that when it was staring me in the face.

**Comment by philipcmonk** [comment]
Woops, sorry for dropping this.  That is indeed the correct answer.  The `{}` construct is used in the doc a decent amount, but I can't find a place where it's defined.  In general, I feel like `docs/hoon/basic`'s introduction of types (spans) without giving the most common syntaxes for them is misguided.  `{}` means the `%cell` type, as you seem to have figured out.

(I know, I know, we "don't have syntax for types" -- except, of course, we do, and we should teach it).

**Comment by ohAitch** [comment]
We don't have syntax for "types", by which most people mean spans; we do
have syntax for molds, which are explicitly called out as another
valid contender for the word.

**Comment by philipcmonk** [comment]
I'm a simple man.  I see `|=  {start/atom end/atom}`, and I see a type signature, containing an argument type.  You can try to argue this is complicated underneath, but it doesn't change the fact that it's _true_.

To be clear, though, your point here is pedantic, not pedagogical, right?  In particular, do you disagree with the proposal that when we introduce the spans in `docs/hoon/basic`, we should introduce commonly used syntaxes for molds whose icon happens to be of the span being described?  (See, isn't that sentence _so much_ easier to understand than "let's put the common syntaxes for types next to the descriptions of those types"?)

**Comment by ohAitch** [comment]
Yes, I was agreeing with you that "we don't have syntax for spans" doesn't
help anyone who's using "type" imprecisely ^-^

**Comment by cgyarvin** [comment]
I would actually introduce this in the FizzBuzz exercise itself.  I think
it's a mistake to try to turn the reference docs into a tutorial -- I don't
think they can be made into a very good tutorial, and part of what makes
reference docs reference docs is that we introduce one concept at a time.

**Comment by philipcmonk** [comment]
Okay, I see your point.  What if, maybe in a sidebar (blockquote), we give a quick example or two of a syntax for creating a mold whose icon is the type you're discussing.  For those who're referring back to this after having seen the mold syntaxes, it would be easier to connect their hands-on experience with the theory.

Also, is there some part of the reference that does introduce mold syntaxes?

**Comment by cgyarvin** [comment]
Sounds great.

It's in the per mold doc I think.  Ie, buried.  Your tutorials are still the best we have...

**Comment by joshuareagan** [comment]
Age has made much of this discussion irrelevant.  Closing this, unless anyone has objections.
