### ISSUE TITLE
No digraph pronunciation guidelines

### ISSUE THREAD

**Issue by Fang-** [urbit/docs#225]
`++` is pronounced `slus` instead of `luslus`. Apparently there's more irregular ones. These should all be documented, for as far as we want to insist they still exist. See also urbit/urbit#593.

**Comment by cgyarvin** [comment]
All of these except slus are terrible, we must rethink

**Comment by joshuareagan** [comment]
Calling all bike-shed painters!

**Comment by belisarius222** [comment]
The only one of those I've ever used or heard is 'slus.'


—
~rovnys-ricfer
https://urbit.org

**Comment by joshuareagan** [comment]
It's not clear to me that all of these need unique names.  I would guess only the arm rune names would get much use.  With the changes, that's: `++`, `+$`, and `+*`.

**Comment by baudtack** [comment]
Captain Bikeshed reporting for duty.

Why do these even need unique names at all?

**Comment by cgyarvin** [comment]
We hear slus in the office pretty regularly.  None of the others.

The point is to mimic the natural contraction that happens through natural language evolution — but we don’t always get it right.

**Comment by baudtack** [comment]
In that case, why not just allow them to arise organically rather than imposing them from the outside, particularly if no one has any good ideas for them and most of them seem to be universally hated. Make this a problem for the Hoonites of the future.

**Comment by cgyarvin** [comment]
That’s always the safe approach!  

But you’ve probably heard of artificially aged scotch.  I’m not saying I’d drink that stuff or anyone should.  But I don’t recommend “white lightning” either...
