### ISSUE TITLE
Missing install dependency

### ISSUE THREAD

**Issue by Fang-** [urbit/docs#226]
`zlib1g-dev` should be mentioned as a dependency. See urbit/urbit#873.

**Comment by xykj61** [comment]
@Fang- In addition to this, we also need `python`, as per urbit/urbit#917, right? I'm assuming we mean `python2`.

**Comment by Fang-** [comment]
Yeah, that seems correct to me.

**Comment by xykj61** [comment]
Fixed with 28ed8bcf081defd60bb40b873df01308b7fb7d55.
