### ISSUE TITLE
Commentary in source code of standard library documentation

### ISSUE THREAD

**Issue by rmariani** [urbit/docs#265]
Each entry in the standard library documentation has an accompanying block of its hoon.hoon source. From hoon.hoon it inherited an uneven pattern of code commentary. 

For example: 
```
++  gte
  ~/  %gte
  :>    unsigned greater than or equals
  :>
  :>  returns whether {a >= b}.
  :>
  :>  a: left hand operand (todo: name)
  :>  b: right hand operand
  |=  [a=@ b=@]
  :>  greater than or equal to?
  ^-  ?
  !(lth a b)
::
```

No code commentary can be seen for `++gte` in  [basic arithmetic](https://urbit.org/docs/hoon/library/1a/) doc, though. This is typical for all the standard library docs. Maybe that's intentional, to make things bite-sized. Or because some of this commentary is redundant with regard to the explanation that is already given in the library. Or perhaps it's that hoon.hoon has been updated with more commentary since then.

So what should be philosophy of source commentary?  My instincts tell me that the obvious approach is to comment the code only where something would benefit from being clarified. However, this would result in standard library documents that take considerably longer to update/write.

Side note: It seems that `:>` is deprecated. Ted introduced me to a new method of leading commentary that can be seen in the [turbo-ford branch](https://github.com/urbit/arvo/blob/ford-turbo/lib/ford-turbo.hoon).

**Comment by rmariani** [comment]
would appreciate input from @vvisigoth @joshuareagan @keatondunsford

**Comment by cgyarvin** [comment]
My input is: still working on the language features required to specify
this precisely, but for now use the turbo-ford notation

**Comment by xykj61** [comment]
As @belisarius222 hinted at in his earlier comments in urbit/docs#264, in the future, the docs should really auto-generate from the literate documentation in the Arvo source. There's no reason Urbit-flavored markdown and Ford couldn't support this at some date in the future. With that being said, often (almost always), the inline documentation refers to the code that follows it in the next line(s). If this was extracted out of the included source itself into an external paragraph, it might get confusing. I'm fine with the commentary getting included in the source, and then additional commentary can supplement the source in surrounding paragraphs if necessary.

To clarify, the code is in fact more up-to-date than the doc. And as Curtis said, the code and language features are still in progress. Mirroring `ford-turbo` style is definitely the way to go for now.
