### ISSUE TITLE
:cast and :new expand to :bunt, which is not defined

### ISSUE THREAD

**Issue by joemfb** [urbit/docs#28]
`^-` (`:cast`) expands to `:like(:bunt(p) q)` (http://urbit.org/docs/hoon/twig/ket-cast/hep-cast/)

`=|` (`:new`) expands to `:pin(:bunt(p) q)` (http://urbit.org/docs/hoon/twig/tis-flow/bar-new/)

`:bunt` is not specifically defined in the docs. The closes is in http://urbit.org/docs/hoon/twig/buc-mold/:

> Many macros *bunt* a mold, producing `:burn(:per(mold $))`

There's a `$bunt` mold (?), but no keyword sigil for it.

**Comment by chc4** [comment]
We have the bunt variant for a twig, but never actually register it in the keyword parser. Just adding `(word %bunt expa)` to https://github.com/urbit/arvo/blob/master/arvo/hoon.hoon#L9844 should work

Side note, but I'm pretty sure that https://github.com/urbit/arvo/blob/master/arvo/hoon.hoon#L239 is wrong - `%$(_1)` is syntax erroring, and we never actually register a %bunt rune, especially not under `%`. We /used/ to have `$*` for bunt, but that doesn't exist anymore either...

To be honest, you should just use the irregular `*a` no matter what, even in keyword style.

**Comment by cgyarvin** [comment]
Fixed in https://github.com/urbit/arvo/pull/177.
