### ISSUE TITLE
several twigs have truncated explanations

### ISSUE THREAD

**Issue by joemfb** [urbit/docs#30]
- http://urbit.org/docs/hoon/twig/bar-core/cen-core/

> In this trivial example, `g` id ther ...
- http://urbit.org/docs/hoon/twig/cen-call/sig-open/

> In `:call` the core is a gate and we ...
- http://urbit.org/docs/hoon/twig/sig-hint/cen-fast/

> ... must already be registered.

**Comment by galenwp** [comment]
This looks like it could be a mistake in porting some doc forward.  (Which I think we probably did programmatically).  

But, digging in, maybe not.  Here's an ancient version of `|%`: https://github.com/urbit/docs/blob/32c88d6ac989ed96dfeabf79a968686e33a7ed2f/docs/system/hoon/runes/br/brcn.md

**Comment by galenwp** [comment]
Yeah, I thought I could find this by digging around in git history — but now I just have to ask @cgyarvin.  I have a vague memory of a conversation where he decided to rework some twig examples...

**Comment by Fang-** [comment]
Descriptions are no longer truncated.
