### ISSUE TITLE
Docs don't seem to work in latest urbit

### ISSUE THREAD

**Issue by ngzax** [urbit/docs#390]
I am running urbit 0.7.2 on my planet booted from azimuth. I have copied over the latest docs from master into /web but they don't seem to work. All pages just give me 404.

![image](https://user-images.githubusercontent.com/87197/52592103-8872ec00-2e13-11e9-8f07-39283c4c2aaf.png)

I would normally try to ask in urbit, but it seems like all comms are down for me as well. (I have received some sporadic messages but that's it)

**Comment by rmariani** [comment]
This is probably a better issue for github.com/urbit/urbit.org, for future reference

what Arvo branch are you using?

**Comment by ngzax** [comment]
Ah, ok. Having a bit of trouble finding *how* to communicate to anyone ATM. 😁 

Anyway, I built off the the latest master at the time, commit 54ec1258. (2/5).  It build urbit 0.7.2

Thanks.

**Comment by jfranklin9000** [comment]
This looks to be the same as https://github.com/urbit/arvo/issues/1050

There is a fix there (which didn't work for me).

Try joining `~zod/blitz` for latest comms.

**Comment by jfranklin9000** [comment]
Also, https://twitter.com/zodisok has good info about the current state of the net.

**Comment by ngzax** [comment]
Thanks for the info, I appreciate it. I'll assume this is just transitory and more information will be forthcoming. I'll close this.
