### ISSUE TITLE
Hoon tutorial contains a hoon syntax section which is out of date

### ISSUE THREAD

**Issue by baudtack** [urbit/docs#395]
This section https://urbit.org/docs/learn/arvo/hoon/hoon-syntax/ has a portion which is incorrect and should be excised in favor of referencing https://urbit.org/docs/learn/arvo/style/

**Comment by ohAitch** [comment]
Is this what we want in a tutorial before the codebase actually follows it?

**Comment by baudtack** [comment]
Yes. Because all new code should be written this way.

**Comment by rmariani** [comment]
fixed in https://github.com/urbit/docs/pull/396
