### ISSUE TITLE
Explain concepts in Star operations documentation

### ISSUE THREAD

**Issue by msutherl** [urbit/docs#407]
@fche writes in https://github.com/urbit/docs/pull/401:

> Would you consider explaining

> * what "DNS routing" is
> * what setting the the bare IP address (but not UDP port#!) enables
> * and for bonus marks ... whether this is temporary, or whether a ship can learn its own external IP address(es) from upstream peers in the future

**Comment by joemfb** [comment]
@rmariani, we need to catch up on this for the new era.

**Comment by rmariani** [comment]
Yeah, I am available for this whenever

**Comment by rmariani** [comment]
This is being handled in our master plan :)
