### ISSUE TITLE
Docs are impossible to navigate

### ISSUE THREAD

**Issue by philipcmonk** [urbit/docs#412]
Here's a stream-of-consciousness log of me trying to find the docs on molds:

- go to urbit.org, click docs
- scroll through sidebar looking for hoon tutorials or something, there's so much information and so many numbers my eyes can't parse it.  I see "learn/arvo", but don't know where hoon is.
- try skimming the intro page, see "The hoon tutorial", click that
- I see a description of chapters 1 and 2 of the tutorial, but can't figure out how to find them.  There's no links, no list of sections at the bottom or anything.  I suspect it's in the sidebar somewhere, but I can't find it
- Try clicking the "Reference" link, get a 404: https://urbit.org/docs/learn/arvo/hoon/link.  "Hoon workbook" link doesn't work either.

I could probably ctrl-f hoon and find stuff in the sidebar, but I shouldn't have to do that

- also https://urbit.org/docs/getting-started/azimuth/ links to 404 here: https://urbit.org/docs/getting-started/azimuth/docs/getting-started is a

**Comment by flowerornament** [comment]
I have the green light to work on the website over the next couple of months, so we'll have a chance to fix some things. Meeting Monday with @galenwp and @rmariani to talk about some of the main issues with docs specifically.

**Comment by rmariani** [comment]
The navbar is definitely a tough issue to wrangle with, so I feel your pain @philipcmonk. We have some solutions in mind already, so stay tuned

**Comment by rmariani** [comment]
The navbar is definitely a tough issue to wrangle with, so I feel your pain @philipcmonk. We have some solutions in mind already, so stay tuned
