### ISSUE TITLE
Comprehensively document need for urbit port 80 access

### ISSUE THREAD

**Issue by msutherl** [urbit/docs#435]
We have a soft assumption that Urbit is running on port 80, i.e. for access to Landscape.

We added a note about enabling access to port 80 on Ubuntu (https://github.com/urbit/docs/pull/432), but this should be documented for all distributions.

**Comment by joemfb** [comment]
This is only strictly necessary for stars. Also advised for galaxies, so that they can get a LetsEncrypt certificate. Not at all necessary for planets, as they are always proxied through the star when accessed via `arvo.network`.

**Comment by flowerornament** [comment]
This has not been the case for my planet in my experience @joemfb, which makes me wonder if I'm misunderstanding what's going on. Possibly my ship didn't have permission to communicate over 8080 either and urbit defaults to saying it's on 8080 even if it can't connect at all.

**Comment by baudtack** [comment]
@joemfb is this still true given that all the lets encrypt stuff was killed?

**Comment by joemfb** [comment]
The need for this documentation would still exist were that given -- but that is not given, so the need exists *even more*. The relevant docs are in progress, I'll send details.
