### ISSUE TITLE
Users may need to re-open port 80 when urbit is upgraded

### ISSUE THREAD

**Issue by msutherl** [urbit/docs#483]
I needed to run `sudo setcap 'cap_net_bind_service=+ep' $(which urbit)` on my machine to get urbit to connect on port 80, potentially because of the upgrade to 0.7.4. We might want to mention this in the documentation somewhere – perhaps a section on upgrading?

**Comment by joemfb** [comment]
That's (re-)applying the "capability" to bind port 80 to the urbit binary. Linux capabilities belong to the binary itself, not the name, file path, user, etc. If the binary is replaced, the new binary must also be given the capability (or be run with sudo, or use some kind of port-forwarding, etc.). A section on upgrading sounds like a good idea.

**Comment by jfranklin9000** [comment]
Since the change to `nix` the original command fails because `urbit` it a symlink:
```
$ ls -l $(which urbit)
lrwxrwxrwx. 1 john john 59 Jan  1  1970 /home/john/.nix-profile/bin/urbit -> /nix/store/y8giiik2awgz3a417cwdd1jz1igwy420-urbit/bin/urbit*

$ sudo setcap 'cap_net_bind_service=+ep' $(which urbit)
Failed to set capabilities on file `/home/john/.nix-profile/bin/urbit' (Invalid argument)
usage: setcap [-q] [-v] (-r|-|<caps>) <filename> [ ... (-r|-|<capsN>) <filenameN> ]

 Note <filename> must be a regular (non-symlink) file.
```
Here's a command to can find the binary:
```
$ ls -l $(which urbit) | cut -d '>' -f 2 | cut -c 2-1000 | tr -d '*'
/nix/store/y8giiik2awgz3a417cwdd1jz1igwy420-urbit/bin/urbit
```
I don't know how fragile it is but maybe it can be combined with the original command.

**Comment by matildepark** [comment]
Your instructions are written for people compiling from the repository — the docs refer to people installing release binaries. 

I have also noticed that setcap needs to be run again upon update; usually I have to set it to ~/urbit. 

That said merely stating it needs to be run again when updating is simpler than the nix instructions here — but they may have a place in CONTRIBUTING.md for people running from the repo. (Perhaps we need “updating Urbit” docs incl. breach info?)

As to when development stream needs to use port 80, I suppose it might happen? macOS keeps 80 open so I only have to engage with setcap on my ship’s AWS.
