### ISSUE TITLE
Restore runes to navbar links

### ISSUE THREAD

**Issue by baudtack** [urbit/docs#510]
Somehow the actual runes got removed from the tiles of navbar links for the runes section. These are absolutely needed. I'm not looking for the runes that make cores, I'm looking for | runes.

**Comment by flowerornament** [comment]
@baudtack this is actually a docs issue and you can fix it yourself by just adding the runes back to the page titles https://github.com/urbit/docs/tree/master/reference/hoon-expressions/rune
