### ISSUE TITLE
"Note: Do not, under any circumstances, delete your pier" is incorrect

### ISSUE THREAD

**Issue by msutherl** [urbit/docs#587]
The booting the ships docs say "never delete your pier," but this page may often be seen in the context of a network breach, which is indeed a circumstance in which you should delete (or archive) your pier.

The larger issue may be that we should incorporate information about what to do in a network breach on this page.

https://urbit.org/docs/getting-started/booting-a-ship/

**Comment by rmariani** [comment]
I don't think that that's a good place for breach documentation. Such documentation will have its own page.

**Comment by Fang-** [comment]
Since we've seen reports of people trying to boot post-breach with their old piers, we might still want to add a notice there, "the exception is network breaches, click here for more info" or similar.

**Comment by rmariani** [comment]
This PR addresses this issue: https://github.com/urbit/docs/pull/596
