### ISSUE TITLE
"dns-proxying" is a confusing title

### ISSUE THREAD

**Issue by joemfb** [urbit/docs#623]
Presumably this came about through the conflation of the arvo.network DNS record bindings, and the entirely-separate TCP proxying that depended upon those records. I think the title should be something like "Arvo.network DNS" (or "domain names" or "subdomains" ...). DNS and proxying are two almost entirely unrelated things, and the term "dns-proxying" suggests a proxy server for a dns server, which is very misleading.

**Comment by baudtack** [comment]
fixed in pr 624

**Comment by joemfb** [comment]
I just checked the docs to help someone get DNS setup, and I see that the old terminology is back.
