### ISSUE TITLE
eth-manage is no more

### ISSUE THREAD

**Issue by philipcmonk** [urbit/docs#663]
In the troubleshooting page, `eth-manage` isn't what you use anymore.  The replacement is `:azimuth-tracker|listen ~ %app %azimuth-tracker` to sync from an ethereum node for all ships and `:azimuth-tracker|listen ~[~zod ~marzod] %app %azimuth-tracker` to sync from an ethereumnode for a list of ships (~zod and ~marzod in this case).

**Comment by rmariani** [comment]
Right, I will fix this now, thanks

**Comment by rmariani** [comment]
fixed: https://github.com/urbit/docs/pull/664
