### ISSUE TITLE
Document |knob

### ISSUE THREAD

**Issue by philipcmonk** [urbit/docs#678]
`|knob` allows you to set the verbosity of different error messages.  It's useful to silence errors that you can't/needn't do anything about.  This is often the case [here](https://urbit.org/docs/tutorials/ship-troubleshooting/#i-keep-getting-an-ames-error-stack-trace), so somewhere we should describe how to use it.

The command has the form `|knob %error-tag %level`.  `%error-tag` describes the error in question and is usually printed at the top of the stack trace (eg in "crud: %hole event failed", `%hole` is the error tag).  `%level` is one of:

- `%hush`: no output
- `%soft`: one line of output, just containing the error tag
- `%loud`: full output.

So for example, to silence all ames packet-related errors, try `|knob %hole %hush`.

**Comment by rmariani** [comment]
Addressed in https://github.com/urbit/docs/pull/682

**Comment by philipcmonk** [comment]
Thanks!

FYI, if you put "Fixes urbit/docs#678" in the PR text or commit message, then when it
gets merged to master it'll automatically close this issue with a link to
that PR.

**Comment by rmariani** [comment]
Cool, thanks for the tip!
