### ISSUE TITLE
Personal breach instructions are a bit confusing

### ISSUE THREAD

**Issue by galenwp** [urbit/docs#708]
To find the personal breach instructions, first I went to the operating manual. Turns out those instructions are there — good thing we have search. Perhaps we should somehow link to the 'guide to breaches' from the operator manual? Seems a little confusing to duplicate this information.

Anyway, once in the 'guide to breaches' I think things have fallen out of date with hosted bridge. Where do I go? What do I click? I think I should go to admin/permissions then update my networking keys? I'm actually not sure. Do I check the box once I'm there?

Seems like this could be simpler on the Bridge end too — but in the meantime we should make sure the instructions are correct.

**Comment by philipcmonk** [comment]
Everyone always asks me about if the checkbox is correct, it'd be nice to fix it.  I'm told its name is "Trigger a new continuity era".

**Comment by joemfb** [comment]
It seems like there should be two different paths through the UI, not just a checkbox. While the implementation difference is a single bit flag, the use-cases are dramatically different: key-rotation vs save-my-ship.

**Comment by vvisigoth** [comment]
Yeah, this is what @galenwp and I discussed. Now that we have this ripcord,
would be good to have a "Save my ship" functionality. Even calling it
"individual breach" requires you to know what a normal breach is. With a
little luck, our children will never even hear the term.
—
~poldec-tonteg
http://urbit.org

**Comment by philipcmonk** [comment]
Although everybody says "breach" when they're telling noobs to do it, so not having the word "breach" is most of the reason even people who notice the checkbox don't know if it's right to click it.

**Comment by vvisigoth** [comment]
OK, I've made a bridge issue to make this its own flow. In the
meantime, @rmariani can you make sure that the instructions are brough up
to date with current Bridge, including the new checkbox name as per this PR?

https://github.com/urbit/bridge/pull/339/files
—
~poldec-tonteg
http://urbit.org

**Comment by rmariani** [comment]
Yup, playing around with Bridge now
