### ISSUE TITLE
Threads undocumented, 2.7 Gall is outdated

### ISSUE THREAD

**Issue by philipcmonk** [urbit/docs#737]
(after the breach)

Tapps and the async monad are replaced by the concept of "threads", which are very similar but more coherent.  Here's some description of them: [thread.txt](https://github.com/urbit/docs/files/3890365/thread.txt)

Some things to change include the "async monad" walkthrough and the "using your ship" page, where it should be explained that you can run a thread with `-thread` similar to `+generator`.

**Comment by Fang-** [comment]
More broadly, the 2.7 Gall section of the docs hasn't been updated for static gall (within which the async monad -> spider transition happened iirc) at all, rendering all the current teachings and examples unusable.

**Comment by Fang-** [comment]
Gentle ping for this to be picked up soon. People keep hitting this, and these are important "getting started with urbit dev" docs.

**Comment by gusmacaulay** [comment]
is there a "workaround" for this? some other example to look at perhaps?

**Comment by jfranklin9000** [comment]
Try this for newer gall docs: https://urbit.org/docs/tutorials/arvo/gall/

**Comment by drbeefsupreme** [comment]
See also https://urbit.org/docs/reference/vane-apis/gall/

**Comment by rmariani** [comment]
bandaid so readers aren't mislead: https://github.com/urbit/docs/blob/rmariani-patch-6/tutorials/hoon/gall.md
