### ISSUE TITLE
|nuke has been removed

### ISSUE THREAD

**Issue by joemfb** [urbit/docs#751]
final remnants in urbit/urbit#2051

/cc @belisarius222

**Comment by rmariani** [comment]
Has anything replaced it?

**Comment by belisarius222** [comment]
No.  Ames is supposed to actually work now.  We do have diagnostics to run in case of issues (e.g. +timers and |ames-verb %snd %rcv %msg %odd %rot), but there are no longer scripts that attempt Herculean feats of resynchronization.

—
~rovnys-ricfer
https://urbit.org

**Comment by rmariani** [comment]
https://github.com/urbit/docs/pull/790
