### ISSUE TITLE
URL to Technical Overview 404's

### ISSUE THREAD

**Issue by bencalder** [urbit/docs#772]
`https://urbit.org/understanding-urbit/technical-overview`

This has been linked to frequently, so if the URL scheme has changed we should at least have a redirect.

**Comment by bencalder** [comment]
Just realized there's a separate repo for `urbit.org`. Let me know if this issue would be better created there.

**Comment by matildepark** [comment]
It’s an urbit.org thing, unless we’re using a docs page as the page we refer to. I can set up an alias, just gotta think real quick on what would be the best surrogate ...

**Comment by matildepark** [comment]
Added an alias to our current closest Technical Overview page in a54ed69a4c39a1318b1a87363886e36c0f321d28.

**Comment by bencalder** [comment]
Did the original Technical Overview page get wiped out entirely?

It was part of the `urbit.org` main intro flow and is also linked from the site’s footer.

**Comment by matildepark** [comment]
You’re right on the footer — we should amend the footer for current UU flow. We basically redid the entire intro flow last week. I suppose we more or less front-load “what Urbit is” now.

— 
~haddef-sigwen
http://urbit.org

**Comment by bencalder** [comment]
Ah got it. Thanks! 👍🏻
