### ISSUE TITLE
Library docs aren't searchable with ^f

### ISSUE THREAD

**Issue by cgyarvin** [urbit/docs#78]
A single-page rendering would be much desired.  (courtesy of ~hobten-hinrym).

**Comment by Fang-** [comment]
In the vein of searchability: I heard there used to be a built-in search function. Might be worth bringing that back if it works well enough.

**Comment by galenwp** [comment]
You can see the component here: https://github.com/urbit/tree/blob/master/js/components/SearchComponent.coffee

I think it depended on a renderer or something — which was slow.  @ohAitch would remember.
