### ISSUE TITLE
%get generator documentation is stale

### ISSUE THREAD

**Issue by litpub** [urbit/docs#814]
See: https://github.com/urbit/urbit/issues/2348

The documentation for %get generators is stale because they no longer exist: https://urbit.org/docs/tutorials/hoon/generators/

Per Joe:

> Those docs are stale; %get generators were removed in the "lighter-than-eyre" %eyre rewrite. You can make http requests directly in :dojo (+http://google.com), or from within apps. I don't think there's currently any in-between options.

**Comment by rmariani** [comment]
https://github.com/urbit/docs/pull/879
