### ISSUE TITLE
document how to best run Urbit as a daemon

### ISSUE THREAD

**Issue by lukebuehler** [urbit/docs#843]
It would be good to have an official recommendation how to run Urbit as a daemon/service in Linux, especially when it's hosted on a cloud instance. I have asked several times what people do, and, so far, what I've heard is that people are using `screen`. This is what I've been using now, but I'm not sure if it's the best way.

Could someone from Tlon document how they run their galaxies and stars? And the same for planets?

Maybe this could be also structured as a general "hosting Urbit" tutorial.

**Comment by flowerornament** [comment]
Came here to write this. I think it could be very helpful to mention both `screen` and `tmux` (I use the latter) on the installation page, and I've never seen someone run `urbit` as a service—I suspect it makes debugging cumbersome—but would be cool to have documented if it's a good idea.

**Comment by jfranklin9000** [comment]
If you mention `screen` and `tmux` you might also want to mention `dtach`.  It runs a program in an environment that is protected from the controlling terminal, which is what we use `screen` or `tmux` for.  It also lets your native terminal client, _e.g._ `iTerm2`, handle scrollback.

http://dtach.sourceforge.net/

I've recently been using it (ht to someone in the Urbit Discord) and it does what I want, particularly wrt scrollback.

**Comment by ohAitch** [comment]
Console handles scrollback = while detached all scrollback is lost?

**Comment by jfranklin9000** [comment]
Hmm, not sure.  I'll try an experiment later today, but that could be a problem.

**Comment by jfranklin9000** [comment]
I tested by `|hi`ing from another ship while detached and, alas, the scrollback is lost, so you can disregard my suggestion.

**Comment by drbeefsupreme** [comment]
I'm going to be working on setting this up this week for my own planet, so I'll write it up as I go.

**Comment by drbeefsupreme** [comment]
Instructions for the appeared on install.md in the urbit.org repo at some point in the recent past but I'm overlooking the PR that did it.

Instructions to run urbit as a daemon using King Haskell are still needed, but that will be covered by urbit/docs#919
