### ISSUE TITLE
=> ligature in rune reference

### ISSUE THREAD

**Issue by ohAitch** [urbit/docs#874]
Looks like something fancy about the [header](https://urbit.org/docs/reference/hoon-expressions/rune/tis/#tisgar) font: ![urbit org_docs_reference_hoon-expressions_rune_tis_](https://user-images.githubusercontent.com/1857414/81515263-0c05dc00-92e8-11ea-927e-00435a3a135d.png)
![Screenshot 2020-05-10 18 04 04](https://user-images.githubusercontent.com/1857414/81515396-b2ea7800-92e8-11ea-9c02-288a67033440.png)

**Comment by jfranklin9000** [comment]
It's back.  Again.  https://github.com/urbit/docs/issues/611

**Comment by matildepark** [comment]
In Brave:

![image](https://user-images.githubusercontent.com/20846414/81582571-32765680-937e-11ea-973a-225836197fb3.png)

It looks like Firefox and Chromium browsers respect `font-feature-settings` but Safari doesn't, here. What browser are you using?

**Comment by matildepark** [comment]
(Honestly I think we should be using monospace fonts for these runes anyway. @syzygyzer Thoughts? Would you guys be willing to wrap the runes in `code` backticks?)

**Comment by drbeefsupreme** [comment]
I had commented before I made the PR but my internet went out so I guess it was swallowed. Yeah that's how it should have been all along @matildepark so I went ahead and did it.

**Comment by jfranklin9000** [comment]
None of the browsers work for me.

macOS 10.14.6

Firefox 75.0
<img width="801" alt="tisgar-firefox" src="https://user-images.githubusercontent.com/15039850/81603276-b0912800-9393-11ea-9b4f-21278340eb62.png">

Chrome 81.0.4044.138
<img width="845" alt="tisgar-chrome" src="https://user-images.githubusercontent.com/15039850/81603359-d3bbd780-9393-11ea-8d43-8762b397f4a5.png">

Safari 12.1.2
<img width="846" alt="tisgar-safari" src="https://user-images.githubusercontent.com/15039850/81603402-e504e400-9393-11ea-9897-91337885f336.png">

**Comment by matildepark** [comment]
Oh, I think I know what's going on here — same as https://github.com/urbit/urbit.org/pull/404

I'll look into this

**Comment by ohAitch** [comment]
MDN [recommends](https://developer.mozilla.org/en-US/docs/Web/CSS/font-feature-settings) against `font-feature-settings`:
> **Note:** Whenever possible, Web authors should instead use the [`font-variant`](https://developer.mozilla.org/en-US/docs/Web/CSS/font-variant) shorthand property or an associated longhand property such as [`font-variant-ligatures`](https://developer.mozilla.org/en-US/docs/Web/CSS/font-variant-ligatures),

**Comment by matildepark** [comment]
Oh wait why should I look into this — urbit/docs#876 fixes this issue
